server:
  port: 8083

spring:
  application:
    name: logement
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:postgresql://localhost:5432/logement_db
    username: postgres
    password: f
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: mon-secret-jwt-256-bits-minimum-dschang-2026-francko

# --- CONFIGURATION SWAGGER
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html